#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
#   Only displays the username, user id, and user home directory path.

passwd_file="/etc/passwd"

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "$passwd_file"
